partial class UIds
{
	/// <summary>
	/// ALLIANCE_BATTLE_CLEAR_MESSAGE
	/// </summary>
	public const string ALLIANCE_BATTLE_CLEAR_MESSAGE="ALLIANCE_BATTLE_CLEAR_MESSAGE";
	/// <summary>
	/// ALLIANCE_BATTLE_ENDED_MESSAGE
	/// </summary>
	public const string ALLIANCE_BATTLE_ENDED_MESSAGE="ALLIANCE_BATTLE_ENDED_MESSAGE";
	/// <summary>
	/// ALLIANCE_BATTLE_NORMAL_MODE_READY
	/// </summary>
	public const string ALLIANCE_BATTLE_NORMAL_MODE_READY="ALLIANCE_BATTLE_NORMAL_MODE_READY";
	/// <summary>
	/// ALLIANCE_BATTLE_EXTREME_MODE_READY
	/// </summary>
	public const string ALLIANCE_BATTLE_EXTREME_MODE_READY="ALLIANCE_BATTLE_EXTREME_MODE_READY";
	/// <summary>
	/// ALLIANCE_BATTLE_HERO_SELECTION_DYN
	/// </summary>
	public const string ALLIANCE_BATTLE_HERO_SELECTION_DYN="ALLIANCE_BATTLE_HERO_SELECTION_DYN";
	/// <summary>
	/// ALLIANCE_BATTLE_HERO_SELECTION_HEADER
	/// </summary>
	public const string ALLIANCE_BATTLE_HERO_SELECTION_HEADER="ALLIANCE_BATTLE_HERO_SELECTION_HEADER";
	/// <summary>
	/// ALLIANCE_BATTLE_NORMAL_MODE_START
	/// </summary>
	public const string ALLIANCE_BATTLE_NORMAL_MODE_START="ALLIANCE_BATTLE_NORMAL_MODE_START";
	/// <summary>
	/// ALLIANCE_BATTLE_EXTREME_MODE_START
	/// </summary>
	public const string ALLIANCE_BATTLE_EXTREME_MODE_START="ALLIANCE_BATTLE_EXTREME_MODE_START";
	/// <summary>
	/// ALLIANCE_BATTLE_MODE_HEADER
	/// </summary>
	public const string ALLIANCE_BATTLE_MODE_HEADER="ALLIANCE_BATTLE_MODE_HEADER";
	/// <summary>
	/// ALLIANCE_BATTLE_END_SCREEN_HOME
	/// </summary>
	public const string ALLIANCE_BATTLE_END_SCREEN_HOME="ALLIANCE_BATTLE_END_SCREEN_HOME";
	/// <summary>
	/// ALLIANCE_BATTLE_NOTICE_THREE_CHARACTERS_REQUIRED
	/// </summary>
	public const string ALLIANCE_BATTLE_NOTICE_THREE_CHARACTERS_REQUIRED="ALLIANCE_BATTLE_NOTICE_THREE_CHARACTERS_REQUIRED";
}
