partial class UIds
{
	/// <summary>
	/// CHALLENGES_DAILY_TRIVIA_TAB
	/// </summary>
	public const string CHALLENGES_DAILY_TRIVIA_TAB="CHALLENGES_DAILY_TRIVIA_TAB";
	/// <summary>
	/// CHALLENGES_DAILY_START_BUTTON
	/// </summary>
	public const string CHALLENGES_DAILY_START_BUTTON="CHALLENGES_DAILY_START_BUTTON";
	/// <summary>
	/// CHALLENGES_DAILY_TRIVIA_ANSWER_DYN
	/// </summary>
	public const string CHALLENGES_DAILY_TRIVIA_ANSWER_DYN="CHALLENGES_DAILY_TRIVIA_ANSWER_DYN";
	/// <summary>
	/// CHALLENGES_DAILY_TRIVIA_QUESTION
	/// </summary>
	public const string CHALLENGES_DAILY_TRIVIA_QUESTION="CHALLENGES_DAILY_TRIVIA_QUESTION";
	/// <summary>
	/// CHALLENGES_DAILY_TRIVIA_CLOSE_BUTTON
	/// </summary>
	public const string CHALLENGES_DAILY_TRIVIA_CLOSE_BUTTON="CHALLENGES_DAILY_TRIVIA_CLOSE_BUTTON";
	/// <summary>
	/// CHALLENGES_DAILY_TRIVIA_QUESTION_STATUS
	/// </summary>
	public const string CHALLENGES_DAILY_TRIVIA_QUESTION_STATUS="CHALLENGES_DAILY_TRIVIA_QUESTION_STATUS";
}
