partial class UIds
{
	/// <summary>
	/// CONTENT_STATUS_BOARD_ITEM_NAME_DYN
	/// </summary>
	public const string CONTENT_STATUS_BOARD_ITEM_NAME_DYN="CONTENT_STATUS_BOARD_ITEM_NAME_DYN";
	/// <summary>
	/// CONTENT_STATUS_BOARD_ITEM_NAME_COMPLETED_DYN
	/// </summary>
	public const string CONTENT_STATUS_BOARD_ITEM_NAME_COMPLETED_DYN="CONTENT_STATUS_BOARD_ITEM_NAME_COMPLETED_DYN";
	/// <summary>
	/// CONTENT_STATUS_BOARD_ITEM_STATUS_DYN
	/// </summary>
	public const string CONTENT_STATUS_BOARD_ITEM_STATUS_DYN="CONTENT_STATUS_BOARD_ITEM_STATUS_DYN";
	/// <summary>
	/// CONTENT_STATUS_BOARD_BUTTON
	/// </summary>
	public const string CONTENT_STATUS_BOARD_BUTTON="CONTENT_STATUS_BOARD_BUTTON";
	/// <summary>
	/// CONTENT_STATUS_BOARD_MENU_HEADER
	/// </summary>
	public const string CONTENT_STATUS_BOARD_MENU_HEADER="CONTENT_STATUS_BOARD_MENU_HEADER";
	/// <summary>
	/// CONTENT_STATUS_BOARD_DRAG_END
	/// </summary>
	public const string CONTENT_STATUS_BOARD_DRAG_END="CONTENT_STATUS_BOARD_DRAG_END";
	/// <summary>
	/// CONTENT_STATUS_BOARD_DRAG_START
	/// </summary>
	public const string CONTENT_STATUS_BOARD_DRAG_START="CONTENT_STATUS_BOARD_DRAG_START";
	/// <summary>
	/// CONTENT_STATUS_BOARD_GOTO_MAINSCREEN
	/// </summary>
	public const string CONTENT_STATUS_BOARD_GOTO_MAINSCREEN="CONTENT_STATUS_BOARD_GOTO_MAINSCREEN";
}
