partial class UIds
{
	/// <summary>
	/// DIMENSION_MISSION_REWARD_STATUS
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_STATUS="DIMENSION_MISSION_REWARD_STATUS";
	/// <summary>
	/// DIMENSION_MISSION_READY_BUTTON
	/// </summary>
	public const string DIMENSION_MISSION_READY_BUTTON="DIMENSION_MISSION_READY_BUTTON";
	/// <summary>
	/// DIMENSION_MISSION_CLEAR_BUTTON
	/// </summary>
	public const string DIMENSION_MISSION_CLEAR_BUTTON="DIMENSION_MISSION_CLEAR_BUTTON";
	/// <summary>
	/// DIMENSION_MISSION_NOTICE_USE_HIDDEN_TICKET_DONT_USE
	/// </summary>
	public const string DIMENSION_MISSION_NOTICE_USE_HIDDEN_TICKET_DONT_USE="DIMENSION_MISSION_NOTICE_USE_HIDDEN_TICKET_DONT_USE";
	/// <summary>
	/// DIMENSION_MISSION_NOTICE_USE_HIDDEN_TICKET
	/// </summary>
	public const string DIMENSION_MISSION_NOTICE_USE_HIDDEN_TICKET="DIMENSION_MISSION_NOTICE_USE_HIDDEN_TICKET";
	/// <summary>
	/// DIMENSION_MISSION_USE_10_CLEAR_TICKET_BUTTON
	/// </summary>
	public const string DIMENSION_MISSION_USE_10_CLEAR_TICKET_BUTTON="DIMENSION_MISSION_USE_10_CLEAR_TICKET_BUTTON";
	/// <summary>
	/// DIMENSION_MISSION_USE_1_CLEAR_TICKET_BUTTON
	/// </summary>
	public const string DIMENSION_MISSION_USE_1_CLEAR_TICKET_BUTTON="DIMENSION_MISSION_USE_1_CLEAR_TICKET_BUTTON";
	/// <summary>
	/// DIMENSION_MISSION_USE_CLEAR_TICKETS_QUESTION
	/// </summary>
	public const string DIMENSION_MISSION_USE_CLEAR_TICKETS_QUESTION="DIMENSION_MISSION_USE_CLEAR_TICKETS_QUESTION";
	/// <summary>
	/// DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_TITLE
	/// </summary>
	public const string DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_TITLE="DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_TITLE";
	/// <summary>
	/// DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_STATUS
	/// </summary>
	public const string DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_STATUS="DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_STATUS";
	/// <summary>
	/// DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_USE_1_TICKET
	/// </summary>
	public const string DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_USE_1_TICKET="DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_USE_1_TICKET";
	/// <summary>
	/// DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_USE_10_TICKET
	/// </summary>
	public const string DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_USE_10_TICKET="DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_USE_10_TICKET";
	/// <summary>
	/// DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_CLOSE
	/// </summary>
	public const string DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_CLOSE="DIMENSION_MISSION_CLEAR_TICKET_ENDSCREEN_CLOSE";
	/// <summary>
	/// DIMENSION_MISSION_BACK_BUTTON
	/// </summary>
	public const string DIMENSION_MISSION_BACK_BUTTON="DIMENSION_MISSION_BACK_BUTTON";
	/// <summary>
	/// DIMENSION_MISSION_REWARD_COLLECT_BUTTON
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_COLLECT_BUTTON="DIMENSION_MISSION_REWARD_COLLECT_BUTTON";
	/// <summary>
	/// DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE_OK
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE_OK="DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE_OK";
	/// <summary>
	/// DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE="DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE";
	/// <summary>
	/// DIMENSION_MISSION_REWARD_CLOSE_AD
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_CLOSE_AD="DIMENSION_MISSION_REWARD_CLOSE_AD";
	/// <summary>
	/// DIMENSION_MISSION_REWARD_CLOSE_AD_NOTICE_OK
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_CLOSE_AD_NOTICE_OK="DIMENSION_MISSION_REWARD_CLOSE_AD_NOTICE_OK";
	/// <summary>
	/// DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE_CLOSE
	/// </summary>
	public const string DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE_CLOSE="DIMENSION_MISSION_REWARD_ACQUIRED_NOTICE_CLOSE";
}
