partial class UIds
{
	/// <summary>
	/// EPIC_QUEST_DUAL_MISSION_LEFT
	/// </summary>
	public const string EPIC_QUEST_DUAL_MISSION_LEFT="EPIC_QUEST_DUAL_MISSION_LEFT";
	/// <summary>
	/// EPIC_QUEST_DUAL_MISSION_RIGHT
	/// </summary>
	public const string EPIC_QUEST_DUAL_MISSION_RIGHT="EPIC_QUEST_DUAL_MISSION_RIGHT";
	/// <summary>
	/// EPIC_QUEST_ENDSCREEN_MISION_NAME
	/// </summary>
	public const string EPIC_QUEST_ENDSCREEN_MISION_NAME="EPIC_QUEST_ENDSCREEN_MISION_NAME";
	/// <summary>
	/// EPIC_QUEST_ENDSCREEN_HOME_BUTTON
	/// </summary>
	public const string EPIC_QUEST_ENDSCREEN_HOME_BUTTON="EPIC_QUEST_ENDSCREEN_HOME_BUTTON";
	/// <summary>
	/// EPIC_QUEST_ENDSCREEN_HOME_BUTTON_IMAGE
	/// </summary>
	public const string EPIC_QUEST_ENDSCREEN_HOME_BUTTON_IMAGE="EPIC_QUEST_ENDSCREEN_HOME_BUTTON_IMAGE";
	/// <summary>
	/// EPIC_QUEST_ENDSCREEN_NOTICE_ALL_ENTRIES_USED
	/// </summary>
	public const string EPIC_QUEST_ENDSCREEN_NOTICE_ALL_ENTRIES_USED="EPIC_QUEST_ENDSCREEN_NOTICE_ALL_ENTRIES_USED";
	/// <summary>
	/// EPIC_QUEST_ENDSCREEN_NOTICE_ALL_ENTRIES_USED_OK_BUTTON
	/// </summary>
	public const string EPIC_QUEST_ENDSCREEN_NOTICE_ALL_ENTRIES_USED_OK_BUTTON="EPIC_QUEST_ENDSCREEN_NOTICE_ALL_ENTRIES_USED_OK_BUTTON";
}
