partial class UIds
{
	/// <summary>
	/// GENERIC_MISSION_START
	/// </summary>
	public const string GENERIC_MISSION_START="GENERIC_MISSION_START";
	/// <summary>
	/// GENERIC_MISSION_ITEM_LIMIT_REACHED_NOTICE
	/// </summary>
	public const string GENERIC_MISSION_ITEM_LIMIT_REACHED_NOTICE="GENERIC_MISSION_ITEM_LIMIT_REACHED_NOTICE";
	/// <summary>
	/// GENERIC_MISSION_ITEM_LIMIT_REACHED_NOTICE_OK_BUTTON
	/// </summary>
	public const string GENERIC_MISSION_ITEM_LIMIT_REACHED_NOTICE_OK_BUTTON="GENERIC_MISSION_ITEM_LIMIT_REACHED_NOTICE_OK_BUTTON";
	/// <summary>
	/// GENERIC_MISSION_INVENTORY_FULL_NOTICE
	/// </summary>
	public const string GENERIC_MISSION_INVENTORY_FULL_NOTICE="GENERIC_MISSION_INVENTORY_FULL_NOTICE";
	/// <summary>
	/// GENERIC_MISSION_MISSION_SUCCESS
	/// </summary>
	public const string GENERIC_MISSION_MISSION_SUCCESS="GENERIC_MISSION_MISSION_SUCCESS";
	/// <summary>
	/// GENERIC_MISSION_NOTICE_DISCONNECTED
	/// </summary>
	public const string GENERIC_MISSION_NOTICE_DISCONNECTED="GENERIC_MISSION_NOTICE_DISCONNECTED";
	/// <summary>
	/// GENERIC_MISSION_NOTICE_DISCONNECTED_OK
	/// </summary>
	public const string GENERIC_MISSION_NOTICE_DISCONNECTED_OK="GENERIC_MISSION_NOTICE_DISCONNECTED_OK";
}
