partial class UIds
{
	/// <summary>
	/// INVENTORY_TAB_MATERIAL
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL="INVENTORY_TAB_MATERIAL";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_ITEM_GRID
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_ITEM_GRID="INVENTORY_TAB_MATERIAL_ITEM_GRID";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_SELECTED_ITEM_NAME
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_SELECTED_ITEM_NAME="INVENTORY_TAB_MATERIAL_SELECTED_ITEM_NAME";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_URU_COMBINE_ALL
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_URU_COMBINE_ALL="INVENTORY_TAB_MATERIAL_URU_COMBINE_ALL";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_URU_COMBINE_X_TIMES_BUTTON
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_URU_COMBINE_X_TIMES_BUTTON="INVENTORY_TAB_MATERIAL_URU_COMBINE_X_TIMES_BUTTON";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_URU_COMBINE_SKIP
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_URU_COMBINE_SKIP="INVENTORY_TAB_MATERIAL_URU_COMBINE_SKIP";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_URU_COMBINE_OK
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_URU_COMBINE_OK="INVENTORY_TAB_MATERIAL_URU_COMBINE_OK";
	/// <summary>
	/// INVENTORY_TAB_MATERIAL_URU_COMBINE_ALL_CANCEL
	/// </summary>
	public const string INVENTORY_TAB_MATERIAL_URU_COMBINE_ALL_CANCEL="INVENTORY_TAB_MATERIAL_URU_COMBINE_ALL_CANCEL";
	/// <summary>
	/// INVENTORY_TAB_CUSTOM_GEAR
	/// </summary>
	public const string INVENTORY_TAB_CUSTOM_GEAR="INVENTORY_TAB_CUSTOM_GEAR";
	/// <summary>
	/// INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE
	/// </summary>
	public const string INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE="INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE";
	/// <summary>
	/// INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE_OK
	/// </summary>
	public const string INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE_OK="INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE_OK";
	/// <summary>
	/// INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE_RESULT_OK
	/// </summary>
	public const string INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE_RESULT_OK="INVENTORY_TAB_CUSTOM_GEAR_QUICK_UPGRADE_RESULT_OK";
}
