partial class UIds
{
	/// <summary>
	/// LEGENDARY_BATTLE_NAME_DYN
	/// </summary>
	public const string LEGENDARY_BATTLE_NAME_DYN="LEGENDARY_BATTLE_NAME_DYN";
	/// <summary>
	/// LEGENDARY_BATTLE_NORMAL_MODE_BUTTON
	/// </summary>
	public const string LEGENDARY_BATTLE_NORMAL_MODE_BUTTON="LEGENDARY_BATTLE_NORMAL_MODE_BUTTON";
	/// <summary>
	/// LEGENDARY_BATTLE_MISSION_ENTER
	/// </summary>
	public const string LEGENDARY_BATTLE_MISSION_ENTER="LEGENDARY_BATTLE_MISSION_ENTER";
	/// <summary>
	/// LEGENDARY_BATTLE_MISSION_START
	/// </summary>
	public const string LEGENDARY_BATTLE_MISSION_START="LEGENDARY_BATTLE_MISSION_START";
	/// <summary>
	/// LEGENDARY_BATTLE_MISSION_SKIP_INTRO
	/// </summary>
	public const string LEGENDARY_BATTLE_MISSION_SKIP_INTRO="LEGENDARY_BATTLE_MISSION_SKIP_INTRO";
	/// <summary>
	/// LEGENDARY_BATTLE_MISSION_SUCCESS
	/// </summary>
	public const string LEGENDARY_BATTLE_MISSION_SUCCESS="LEGENDARY_BATTLE_MISSION_SUCCESS";
	/// <summary>
	/// LEGENDARY_BATTLE_ENDSCREEN_REPEAT_RUN
	/// </summary>
	public const string LEGENDARY_BATTLE_ENDSCREEN_REPEAT_RUN="LEGENDARY_BATTLE_ENDSCREEN_REPEAT_RUN";
}
